#+TITLE: Todesanzeigen
#+AUTHOR: Melanie Bühler

* Todesanzeige

** Inhalt der Todesanzeige

   - Name (gegebenenfalls Geburtsname) des Verstorbenen
   - Geburts- und Todesdatum
   - Ort des Todes
   - Verfasser der Anzeige
   - Informationen zur Bestattung

   Wenn es in Ordnung ist, dass eine unbekannte Zahl von Trauergästen zur
   Bestattung kommt, so kann man die Informationen über Termin und Ort
   der Bestattung in der Todesanzeige publizieren. So erspart man es
   sich, gesonderte Einladungen zu versenden.

   - Information zur Todesart

   In vielen Todesanzeigen wird kurz auf den Grund für den Todesfall
   eingegangen, zum Beispiel nach langer Krankheit oder durch einen
   tragischen Unfall. Diese Information in der Traueranzeige kann es den
   Hinterbliebenen ersparen, auf Nachfragen reagieren zu müssen, die
   nähere Informationen einfordern.

   - Wünsche für die Abdankungsfeier

   In der Todesanzeige kann man auch auf besondere Wünsche für die Feier
   hinweisen, so zum Beispiel den Verzicht auf Blumen- oder Kranzspenden
   oder die Bitte, am Grab von Beileidsbekundungen abzusehen. Wer möchte,
   kann eine Organisation angeben, an die das für den Kranz gedachte Geld
   gespendet werden kann. Die meisten Trauergäste werden diesen Wünschen
   gerne nachkommen.

** Gliederung der Todesanzeige

*** Verse und Worte des Trostes

**** Christliche Trauersprüche

***** Trauersprüche von Romano Guardini

      #+BEGIN_VERSE
      Der Tod ist die uns zugewandte Seite jenes Ganzen,
      dessen andere Seite Auferstehung heisst.
      #+END_VERSE

***** Trauersprüche von Dietrich Bonhoeffer

      #+BEGIN_VERSE
      Je schöner und voller die Erinnerung, desto schwerer ist die Trennung. Aber die Dankbarkeit
      verwandelt die Erinnerung in eine stille Freude.
      Man trägt das vergangene Schöne nicht wie einen Stachel, sondern wie ein kostbares
      Geschenk in sich.
      #+END_VERSE

      #+BEGIN_VERSE
      Von guten Mächten wundersam geborgen, erwarten wir getrost was kommen mag. Gott ist
      mit uns am Abend und am Morgen und ganz gewiss an jedem neuen Tag
      #+END_VERSE

***** Trauersprüche von Franz von Assisi

      #+BEGIN_VERSE
      Der Tod ist das Tor zum Licht am Ende eines mühsam gewordenen Weges.
      #+END_VERSE

      #+BEGIN_VERSE
      Wer stirbt, erwacht zum ewigen Leben.
      #+END_VERSE

***** Trauersprüche von Papst Johannes XXIII:

      #+BEGIN_VERSE
      Unsere Toten gehören zu den Unsichtbaren, aber nicht zu den Abwesenden.
      #+END_VERSE

***** Trauersprüche aus der Bibel

      #+BEGIN_VERSE
      Befiehl dem Herrn Deine Wege und hoffe auf ihn; er wird`s wohl machen.
      #+END_VERSE

      #+BEGIN_VERSE
      Herr, hier bin ich. Du hast mich gerufen.
      #+END_VERSE

      #+BEGIN_VERSE
      Nun aber bleibt Glaube, Hoffnung, Liebe, diese drei; aber die Liebe ist die grösste unter ihnen.
      #+END_VERSE

      Der Herr ist mein Hirte, mir wird es an nichts mangeln.

      Meine Zeit steht in Deinen Händen.

      Fürchte Dich nicht, denn ich habe Dich erlöst; ich habe Dich bei deinem
      Namen gerufen. Du bist mein.

      Siehe, ich bin bei Euch alle Tage, bis an der Welt Ende!

      In Deine Hände befehle ich meinen Geist; Du hast mich erlöst, Herr, Du treuer Gott.

      Gott vertrauen heisst: Sich verlassen auf das, was man hofft, und fest mit
      dem rechnen, was man nicht sehen kann.

      Der Herr segne Dich und behüte Dich; der Herr lasse sein Angesicht leuchten
      über Dir und sei Dir gnädig; der Herr hebe sein Angesicht über Dich und gebe
      Dir Frieden.

      Jesus spricht: Ich bin der Weg, die Wahrheit und das Leben; niemand kommt
      zum Vater denn durch mich.

      Christus spricht: Ich bin das Licht der Welt.

      Wer mir nachfolgt, wird nicht in der Finsternis bleiben, sondern wird das
      Licht des Lebens haben.

      Ich werde einen Engel schicken, der Dir vorausgeht.
      Er soll Dich auf dem Weg schützen
      und Dich an den Ort bringen,
      den ich bestimmt habe.
      Achte auf ihn und hör auf seine Stimme.

**** Traditionelle Trauersprüche

     Auch wenn wir dir die Ruhe gönnen, ist voller Trauer unser Herz. Dich leiden sehen, ohne
     helfen zu können, war für uns der grösste Schmerz.

     Die Zeit heilt nicht alle Wunden, sie lehrt uns nur mit dem Unbegreiflichen zu leben.

     Du hast gesorgt, du hast geschafft, bis dir die Krankheit nahm die Kraft. Schlicht und einfach
     war dein Leben, treu und fleissig deine Hand, immer helfend für die Deinen, ruhe sanft und
     habe Dank.

     Eine Stimme, die uns vertraut war, schweigt.
     Ein Mensch, der immer für uns da war, lebt nicht mehr.
     Erinnerung ist das, was bleibt.

     Erinnerungen sind kleine Sterne, die tröstend in das Dunkel unserer Trauer leuchten.

     Es gibt im Leben für alles eine Zeit, eine Zeit der Freude, der Stille, der Trauer und eine Zeit
     der dankbaren Erinnerung.

     Ganz still und leise, ohne ein Wort,
     gingst du von deinen Lieben fort,
     du hast ein gutes Herz besessen,
     nun ruht es still, doch unvergessen;
     es ist so schwer, es zu verstehen,
     dass wir dich niemals wiedersehen.

     Keiner geht ganz von uns - er geht nur voraus!

     Unser Herz will Dich halten.
     Unsere Liebe dich umfangen.
     Unser Verstand muss dich gehen lassen.
     Denn deine Kraft war zu Ende
     und deine Erlösung Gnade.

     Gute Menschen gleichen Sternen, sie leuchten noch lange nach ihrem Erlöschen.

     Als Gott sah, dass der Weg zu weit, der Berg zu hoch und der Atem zu schwach wurde, legte
     er seinen Arm um ihn du sagte: Komm her...

     Was du im Leben hast gegeben, dafür ist jeder Dank zu klein. Du hast gesorgt für deine
     Lieben, von früh bis spät, tagaus, tagein. Du warst im Leben so bescheiden, nur Pflicht und
     Arbeit kanntest du, mit allem warst du stets zufrieden drum schlafe sanft in stiller Ruh.

     Das Schönste, was ein Mensch hinterlassen kann, ist ein Lächeln im Gesicht derjenigen, die
     an ihn denken.

     Du siehst den Garten nicht mehr grünen, indem du einst so froh geschafft. Du siehst die
     Blumen nicht mehr blühen, weil der Tod dir nahm die Kraft. Was du aus Liebe uns gegeben,
     dafür ist jeder Dank zu klein. Was wir an dir verloren, das wissen wir nur ganz allein.

     Alles hat seine Zeit. Es gibt eine Zeit der Freude, eine Zeit der Stille, eine Zeit des Schmerzes,
     der Trauer und eine Zeit der dankbaren Erinnerung.

     Wenn Liebe einen Weg zum Himmel fände und Erinnerungen Stufen hätten, dann würden
     wir hinaufsteigen und dich zurückholen!

     Mit den Flügeln der Zeit fliegt die Traurigkeit davon.

     Das einzig wichtige im Leben, sind die Spuren von Liebe, die wir hinterlassen, wenn wir
     weggehen.

     Weine nicht, dass die leuchtenden Tage vorüber sind, lächle, dass sie da waren.

     Weint nicht, weil es vorbei ist, lacht, weil es schön war.

     Du bist nicht mehr da, wo Du warst, aber Du bist überall, wo wir sind.

     Nur, wer vergessen wird, ist tot. Du wirst in unserer Erinnerung immer weiterleben.

     Wir mussten Dich gehen lassen und konnten nichts tun. Still und voll Schmerz hoffen wir, Du
     kannst nun ruhen.

     Dem Auge so fern, dem Herzen ewig nah.

     Wenn man einen geliebten Menschen verliert, gewinnt man einen Schutzengel dazu.

     Ohne dich
     Zwei Worte so leicht zu sagen
     und doch so endlos schwer zu ertragen.

     Der Tod ist nicht das Ende, nicht die Vergänglichkeit,
     der Tod ist nur die Wende, Beginn der Ewigkeit.

     Wir Menschen sind Engel mit nur einem Flügel,
     um fliegen zu können, müssen wir uns umarmen.

     Es kann nicht sein,
     so will uns scheinen,
     der Platz, wo du einst warst,
     ist leer.

     Von den Sternen kommen wir,
     zu den Sternen kehren wir zurück,
     von jetzt bis in alle Ewigkeit.

**** Trauersprüche von Dichtern und Denkern

***** Trauersprüche von Khalil Gibran

      Möglicherweise ist ein Begräbnis unter Menschen eine Hochzeitsfeier unter Engeln.

      Lass mich schlafen, bedecke nicht meine Brust mit Weinen und Seufzen, sprich nicht voll
      Kummer von meinem Weggehen, sondern schliesse deine Augen, und du wirst mich unter
      euch sehen, jetzt und immer.

      Nur Liebe und Tod ändern alle Dinge.

***** Trauersprüche von Albert Schweitzer

      Das schönste Denkmal, was ein Mensch bekommen kann, steht im Herzen der Mitmenschen.

      Das einzig Wichtige im Leben sind die Spuren von Liebe, die wir hinterlassen, wenn wir
      weggehen.

***** Trauerspruch von Anselm von Canterbury

      Nichts ist gewisser als der Tod, nichts ist ungewisser als seine Stunde.

***** Trauersprüche von Antoine de Saint-Exupéy

      Und wenn du dich getröstet hast, (man tröstet sich immer) wirst du froh sein, mich gekannt
      zu haben. Du wirst immer mein Freund sein. Du wirst dich daran erinnern, wie gerne du mit
      mir gelacht hast.

      Man sieht nur mit dem Herzen gut. Das Wesentliche ist für die Augen unsichtbar.

      Wenn du bei Nacht den Himmel anschaust, wird es dir sein, als lachten alle Sterne, weil ich
      auf einem von ihnen wohne, weil ich auf einem von ihnen lache.

***** Trauerspruch von Arthur Schopenhauer

      Ich glaube, dass wenn der Tod unsere Augen schliesst, wir in einem Lichte stehen, von
      welchem unser Sonnenlicht nur der Schatten ist.

      Beim Abschiednehmen kommt ein Moment, in dem man die Trauer so stark vorausfühlt, dass
      der geliebte Mensch schon nicht mehr bei einem ist.

***** Trauersprüche von Aurelius Augustinus

      Unsere Toten sind nicht abwesend, sondern nur unsichtbar. Sie schauen mit ihren Augen
      voller Licht in unsere Augen voller Trauer.

      Auferstehung ist unser Glaube, Wiedersehen unsere Hoffnung, Gedenken unsere Liebe.

      Ihr, die ihr mich so geliebt habt, sehet nicht auf das Leben, dass ich beendet habe, sondern
      auf das, welches ich beginne.

***** Trauerspruch von Berthold Auerbach

      Für einen Vater, dessen Kind stirbt, stirbt die Zukunft. Für ein Kind, dessen Eltern sterben,
      stirbt die Vergangenheit.

***** Trauerspruch von Christian Friedrich Hebbel

      Die Hoffnung ist wie ein Sonnenstrahl, der in ein trauriges Herz dringt. fne es weit und lass
      sie hinein.

***** Trauerspruch von Christian Fürchtegott Gellert

      Lebe, wie du, wenn du stirbst, wünschen wirst, gelebt zu haben.

***** Trauerspruch von Ernest Hemingway

      Nur wenige Menschen sind wirklich lebendig und die, die es sind, sterben nie. Es zählt nicht,
      dass sie nicht mehr da sind. Niemand, den man wirklich liebt, ist jemals tot.

***** Trauerspruch von Franz Kafka

      Man sieht die Sonne langsam untergehen und erschrickt doch, wenn es plötzlich dunkel ist.

***** Trauersprüche von Immanuel Kant

      Wer im Gedächtnis seiner Lieben Lebt, der ist nicht tot, der ist nur fern; tot ist nur, wer
      vergessen wird.

      Den Tod fürchten die am wenigsten, deren Leben am meisten Wert hat.

***** Trauersprüche von Johann Wolfgang von Goethe

      Was man tief in seinem Herzen besitzt, kann man nicht durch den Tod verlieren.

      Wir hoffen immer, und in allen Dingen ist besser hoffen als verzweifeln.

      Eines Morgens wachst du nicht mehr auf. Die Vögel singen, wie sie gestern sangen. Nichts
      ändert diesen neuen Tagesablauf. Nur du bist fortgegangen. Du bist nun frei und unsere
      Tränen wünschen dir Glück.

      Es ist eine Ferne, die war, von der wir kommen. Es ist eine Ferne, die sein wird, zu der wir
      gehen.

      Ach! Ich bin des Treibens müde! Was soll all der Schmerz und Lust? Süsser Friede! Komm, ach
      komm in meine Brust!

      #+BEGIN_VERSE
      Ich bin bei Dir,
      du seist auch noch so ferne,
      du bist mir nah!
      Die Sonne sinkt,
      bald leuchten mir die Sterne.
      O wärst Du da!
      #+END_VERSE

***** Trauerspruch von William Shakespeare

      Wir sind vom gleichen Stoff, aus dem die Träume sind und unser kurzes Leben ist eingebettet
      in einen langen Schlaf.

***** Trauersprüche von Laotse

      Ich bin von euch gegangen nur für einen kurzen Augenblick und garnicht weit. Wenn ihr dahin
      kommt, wohin ich gegangen bin, werdet ihr euch fragen, warum ihr geweint habt.

      Was die Raupe Ende der Welt nennt, nennt der Rest der Welt Schmetterling.

***** Trauerspruch von Emmanuel Geibel

      Ein ewig Rätsel ist das Leben, und ein Geheimnis bleibt der Tod.

***** Trauerspruch von Jean-Paul

      Die Erinnerung ist das einzige Paradies, aus dem wir nicht vertrieben werden können.

***** Trauerspruch von Thomas Mann

      Die Bande der Liebe werden mit dem Tod nicht durchschnitten.

**** Buddhistische Trauersprüche

***** Buddhistischer Trauerspruch von Rabindranath Tagore

      Ich kam an deine Küste als ein Fremdling, ich wohnte in deinem Haus als ein Gast, ich verlasse
      deine Schwelle als ein Freund, meine Erde.

***** Buddhistischer Trauerspruch von Mahatma Gandhi

      Wer einen Fluss überquert, muss die eine Seite verlassen.

***** Buddhistische Trauergedichte

      #+BEGIN_VERSE
      Im Meer des Lebens,
      Meer des Sterbens,
      in beiden müde geworden,
      sucht meine Seele den Berg,
      an dem alle Flut verebbt.
      #+END_VERSE

      #+BEGIN_VERSE
      Der Schatten des Bambus im Mondlicht
      wischt den Staub von den Treppenstufen
      die ganze Nacht lang.
      Nichts ist weggewischt!
      #+END_VERSE

*** Einleitung

    In stiller Trauer teilen wir Ihnen mit, dass ...
    Traurig über den Hinschied und doch dankbar für die Erlösung ...
    Traurig nehmen wir Abschied von ...
    Traurig, aber mit vielen schönen Erinnerungen nehmen wir Abschied von ...
    Mit vielen schönen Erinnerungen nehmen wir Abschied von ...
    Wir nehmen Abschied von ...
    In Liebe und Dankbarkeit nehmen wir Abschied von ...
    Schweren Herzens müssen wir Abschied nehmen von ...
    Wir machen Ihnen die schmerzliche Mitteilung, dass ...
    Fassungslos und voller Schmerz teilen wir Ihnen mit, dass ...
    Ein aussergewöhnlicher Mensch ist von uns gegangen ...
    Aus einem arbeitsamen Leben in Verantwortung für seine Familie und Mitmenschen ist ...

*** Wertschätzung

    lieben / geliebten
    guten / herzensguten
    vorbildlichen / unvergesslichen
    geschätzten / tapferen

*** Beziehung

    | Gattin / Ehefrau           | Gatte / Ehemann        |
    | Lebenspartnerin / Freundin | Lebenspartner / Freund |
    | Mutter/Mami/Mutti/Mama     | Vater/Papi/Vati/Daddy  |
    | Schwiegermutter            | Schwiegervater         |
    | Grossmutter                | Grossvater             |
    | Urgrossmutter              | Urgrossvater           |
    | Tochter                    | Sohn                   |
    | Schwiegertochter           | Schwiegersohn          |
    | Schwester                  | Bruder                 |
    | Schwägerin                 | Schwager               |
    | Tante                      | Onkel                  |
    | Cousine                    | Cousin                 |
    | Gotte                      | Götti                  |
    | Verwandte                  | Verwandter             |
    | Freundin / Bekannte        | Freund / Bekannter     |

*** Abschluss der Einleitung

    #+BEGIN_VERSE
    von uns geschieden / gegangen ist.
    gestorben / verstorben / entschlafen ist.
    uns viel zu früh entrissen wurde.
    von den Altersbeschwerden erlöst worden ist.
    hat uns allzu früh für immer verlassen.
    in Kenntnis zu setzen.
    in aller Stille verlassen.
    #+END_VERSE

*** Persönliche Angaben

    Er ist im Alter von ... Jahren friedlich entschlafen.

    Sie starb nach längerem Leiden im Alter von ... Jahren.

    Er verschied nach kurzer, schwerer Krankheit im ... Lebensjahr.

    Er verschied nach langer, geduldig / bewundernswert ertragener
    Krankheit, jedoch unerwartet rasch im ... Lebensjahr.

    Es war ein langer Weg; auch wenn wir damit rechnen mussten und der
    Tod als Erlöser kam, schmerzt doch die Endgültigkeit.

    Sie wurde im ... Lebensjahr von den Altersbeschwerden erlöst.

    Wir haben mit dir gehofft, gekämpft und gelitten. Jetzt bist du von
    deiner schweren Krankheit erlöst worden.

    Mit grosser Tapferkeit hast du gegen deine Krankheit gekämpft.

    Im Kreise deiner Familie durftest du nun zu Hause friedlich einschlafen.

    Unerwartet hat ihr Herz aufgehört zu schlagen.

    Er starb unerwartet an einem Herzversagen im Alter von ... Jahren.

    Für uns völlig unerwartet ist sie heute Nacht friedlich eingeschlafen.

    Ihr plötzlicher Tod erschüttert uns.

    Ihr Herz hat aufgehört zu schlagen.

    Er starb im ... Lebensjahr an den Folgen eines tragischen Unglücksfalles

    Wir versuchen, deine Entscheidung zu akzeptieren - verstehen werden wir sie nie.

    Er hat erkannt, dass diese Welt nie die seine sein wird.

    Ausserstande, ihm zu helfen, müssen wir seinen Entschluss akzeptieren.

    Sie hat uns in Würde / Stille verlassen, da sie erkannt hat, dass diese Welt nie die ihre sein wird.

*** Würdigung

    In unseren Herzen wirst du weiterleben.

    Wir werden dich nie vergessen und dich immer in unseren Herzen behalten.

    Deine liebenswerte und fröhliche Art bleibt uns unvergessen.

    Schön, dass es dich gab und wir viele wunderbare Momente haben, die wir ewig in unseren Herzen tragen.

    Wir gedenken deiner in Liebe und Dankbarkeit.

    Dankbar sind wir für die Zeit, die wir mit dir erleben
    durften. Traurig sind wir über deinen Tod.

    Alle, die dich kannten, wissen, was wir an dir verloren haben.

    Wir verlieren in dir einen gütigen und verständnisvollen Menschen.

    Ihre Herzlichkeit und ihre Lebensfreude bleiben uns in dankbarer
    Erinnerung.

    Dein fröhliches Wesen und dein herzhaftes Lachen werden wir nie
    vergessen.

    Deine Liebe und Fürsorge werden uns weiter tragen.

    Die Lücke, die du hinterlässt, ist riesig - wir vermissen dich.

    Deine Begeisterungsfähigkeit, dein Humor und deine Grosszügigkeit
    waren einzigartig.

    Voller Energie hast du dein Leben stets in den Dienst deiner
    Mitmenschen gestellt.

    Wir denken mit grosser Liebe und Dankbarkeit an all die wunderschönen
    Erlebnisse, die uns trösten

    und uns immer mit dir verbinden.

    Wir sind unendlich dankbar für die unvergesslich schöne Zeit mit dir.

    Was du für uns alle mit deinem Lebenswerk getan hast, werden wir dir
    nie vergessen.

    Du hast uns allen viel gegeben - wir vermissen dich.

    Du bist von uns gegangen, aber nicht aus unseren Herzen.

    In deinem reich erfüllten Leben bist du stets bescheiden und deinem
    Glauben treu geblieben.

*** Absender

    In stiller Trauer

    In tiefer Trauer

    Die Trauerfamilien

    Die Hinterbliebenen

    Wir vermissen dich

    Im Gedenken

    In liebevoller Erinnerung

    In Liebe Namen der Absender

*** Abschiedsfeier und Beisetzung

    Jeweils mit Wochentag, Datum, Zeit, Ort:

    | Abschiedsfeier        | Trauerfeier        |
    | Abschiedsgottesdienst | Trauergottesdienst |
    | Abdankung             | Beisetzung         |
    | Urnenbeisetzung       | Beerdigung         |

    mit Adressangabe für Navigationsgerät/GPS

    Beispiel: Die Beisetzung findet im engsten Familienkreis statt. Auf
    Wunsch des Verstorbenen findet die Beisetzung im Familienkreis
    statt. Beispiel: Abschiedsfeier: Dienstag, 11. Januar, 14 Uhr in der
    reformierten Stadtkirche Solothurn, anschliessend Urnenbeisetzung auf
    dem Friedhof. Aufbahrung in der Friedhofhalle Solothurn bis Sonntag.

*** Aufbahrung

    Ort Dauer / Ein letzter Besuch in der Friedhofhalle ... ist bis ... möglich.

    Öffnungszeiten

*** Spenden

    Im Sinne des Verstorbenen sind wir dankbar für Spenden an ...

    Wer des lieben Verstorbenen gedenken will, möge ... berücksichtigen.

    Für allfällige Spenden gedenke man des/der / berücksichtige man bitte ...

    Wer den lieben Verstorbenen anders als mit Blumen ehren möchte, gedenke bitte ...

    Wer des Verstorbenen mit einer Spende gedenken möchte, berücksichtige bitte ...

    Wir bitten von Blumenspenden abzusehen und der/des ... zu gedenken.

    Statt Blumen zu spenden, unterstütze man ...

***  Mitteilungen

     Dreissigster: Tag, Datum, Zeit, Ort
     Leidzirkulare werden nur nach auswärts versandt.
     Dient / gilt als Leidzirkular.

* Danksagung

** Gliederung der Danksagung

*** Danksagung

    Wir danken

    Ein herzlicher Dank

    Wir danken von ganzem Herzen

------------- COPY CONTENT HERE ---------------

*** Einleitung

    In den Tagen des Heimgangs

    In den schweren Tagen des plötzlichen Hinschieds

    In diesen Tagen des Abschieds von unserem lieben und unvergesslichen

    In den schweren Tagen des unerwarteten Heimgangs und des Abschieds
    von meinem lieben Gatten und unserem guten Vater

    Für die grosse Anteilnahme, die uns beim Hinschied Für die vielen
    Beweise herzlicher Anteilnahme während der Krankheit und beim
    Hinschied

    Allen, die sich in stiller Trauer mit uns verbunden fühlen und ihre
    liebevolle Anteilnahme auf so vielfältige Weise zum Ausdruck
    brachten, danken wir von Herzen

    Von einem geliebten Menschen Abschied nehmen zu müssen, gehört zu
    den schmerzlichsten Erfahrungen im Leben

*** Name und Daten

    #+BEGIN_VERSE
    Vorname, Name
    Kosenamen
    Berufsbezeichnung / Titel
    im Ruhestand / ehemaliger / alt
    #+END_VERSE

*** Abschluss der Einleitung

    durften wir von unseren Verwandten, Freunden und Bekannten innigste
    Teilnahme erfahren.

    durften wir viel Anteilnahme und Hilfe erfahren.

    sprechen wir allen unseren herzlichen Dank aus.

    sprechen wir mit diesen Zeilen unseren herzlichen Dank aus.

    danken wir von ganzem Herzen.

    in ihrem Leben, vor allem auch in ihrem schweren Leiden Gutes getan
    haben und uns bei ihrem Sterben ihre Teilnahme haben spüren lassen,
    danken wir.

    Es tut gut zu erfahren, wie viel Achtung und Anerkennung unserem
    Vater entgegengebracht wurde.

*** Dank an Personen

   Besonders herzlich danken wir Herrn Dr. med. ...

   Ein besonderer Dank gebührt Herrn Dr. med. ...

   für die ärztliche Betreuung / den ärztlichen Beistand.

   Wir danken den Ärzten für die medizinische Betreuung und dem
   Pflegepersonal / dem Spitexteam ...  für die fürsorgliche Pflege.

   Ein spezielles Dankeschön gilt dem Personal des Alters? und Pflegeheims ..., welches es verstanden hat, dem Verstorbenen durch aufmerksame und liebevolle Begleitung den Alltag trotz seiner
   Altersbeschwerden angenehm zu gestalten.
   Ebenso danken wir Herrn Pfarrer ... für seine trostreichen / einfühlsamen Abschiedsworte.
   Für den feierlich gestalteten Gottesdienst danken wir Frau Pfarrerin ... Für den feierlich gestalteten
   Gottesdienst danken wir Frau Pfarrerin ...
   Es gibt Tage und Stunden im Leben, die jeder durchstehen muss. Aber sich getragen zu wissen von
   Menschen, die uns nahestehen, gibt unendlich viel Kraft. Dankeschön.
   Wir danken allen, die der lieben Verstorbenen in ihrem Leben Gutes erwiesen haben.
   Ein aufrichtiges Dankeschön allen, die dem lieben Verstorbenen in seinem Leben mit Freundschaft
   begegnet sind und ihn während seiner Krankheit begleitet haben.
   Zahllose Hände haben wir geschüttelt. Und waren gerührt. Durften bewegende Briefe, Karten, E-
   Mails und SMS lesen. Uns von gesendeten Statements und Hommagen aufmuntern lassen. Blumen in
   Empfang nehmen. Und Geldspenden weiterleiten.

*** Dank an Vereine, Firmen, Institutionen

    Ganz herzlich danken wir auch den Freunden und Bekannten, die dem lieben Verstorbenen die letzte
    Ehre erwiesen haben.
    Ein herzliches Dankeschön gilt den Nachbarn, Schulkameraden und allen, die an der Abschiedsfeier
    teilgenommen haben.
    Aufrichtigen Dank der Musikgesellschaft ... für ihr ergreifendes Spiel.
    dem Kirchenchor für die würdige Umrahmung der Trauerfeier.
    dem Männerchor für den besinnlichen Vortrag.
    Herzlich danken wir den Fahnendelegationen der Schützen und des Turnvereins sowie allen, die
    unserem lieben Verstorbenen die letzte Ehre erwiesen haben.
    Unser Dank geht auch an die Delegation des ... für ihren letzten Gruss.
    Wir danken der Geschäftsleitung und dem Personal der Firma ... für ihre Unterstützung und ihre
    Anteilnahme.
    Dank für Gaben, Spenden, Sachen, Blumen Wir danken für die zahlreichen Kranz-, Blumen- und
    anderen Spenden sowie die Zuwendungen an wohltätige Institutionen.
    Wir verdanken die vielen letzten Blumengrüsse, die Gaben an wohltätige Institutionen und danken
    allen, die dem lieben Heimgegangenen die letzte Ehre erwiesen haben.
    Wir danken für die Spenden von heiligen Messen, die Zuwendungen an wohltätige Institutionen, die
    prächtigen Blumen und Kränze und das stille Mitleid durch Händedruck und in Briefen.
    Ein herzliches Dankeschön gilt allen, die von unserem lieben Vater Abschied nahmen und in
    liebevoller Anteilnahme ihr Beileid mit stillem Händedruck, Karten, Blumen und Spenden bezeugten.
    Wir verdanken auch die prächtigen Kränze und Blumen, die Zuwendungen an wohltätige
    Institutionen, die Spenden für späteren Grabschmuck sowie die zahlreichen Briefe und Karten.

** Berührung

   Diese Verbundenheit zu spüren, war uns Hilfe und Trost.
   All diese Zeichen der Verbundenheit geben uns Kraft und Trost.
   Alle Beweise der Anteilnahme sind uns Trost in unserem Leid.
   Es ist uns ein Bedürfnis, allen unseren aufrichtigen Dank auszusprechen. Die Anteilnahme war
   überwältigend.
   Zu guter Letzt sind wir uns alle einig: Wenn Willy das alles hätte miterleben dürfen, es wäre ihm
   zweifellos gegangen wie uns. Er hätte geweint. Er hätte gelacht. Und vor allem, er hätte sich riesig
   gefreut.

** Absender

   Ort, im Monat, Jahr
   Absender: die Trauerfamilien, allenfalls mit Namen
   Dreissigster: Wochentag, Datum, Zeit und Ort
